### ISSUE TITLE
Этот проект мертв?

### ISSUE THREAD

**Issue by ghost** [ValeraGin/GinCompiler#1]
Я обнаружил это только сегодня, мне это показалось очень интересным, я хотел бы узнать о нем больше.

**Comment by marcelomelofreitas** [comment]
Yes

**Comment by ValeraGin** [comment]
он был написан мною когда я еще учился в универе - и я сейчас уже не пишу на Паскале =) 

Я бы сказал это раритет и кому то может быть полезен для изучений.

**Comment by ValeraGin** [comment]
https://sourceforge.net/projects/gincompiler/  Last Update: 2013-04-19 =)
